#' @title DrawSummitHeatmaps
#'
#' @description This function plots heatmaps of pre-calculated read counts around the summits of ChIP peaks.
#'
#' @details This function plots heatmaps of pre-calculated read counts around the summits of ChIP peaks.
#'
#' @param counts A list of counts across peak summits generated by SummitHeatmap.
#' @param bamNames A character vector of names to describe the bam files you are using. This should match colnames(counts).
#' @param plotcols The colors for the heatmap. Default is circlize::colorRamp2(c(0, 3), c("white", "darkblue")).
#' @param nicebamNames A character vector of short names to describe the bam files you are using. Needs to be the same length as bamNames.
#'

#' @return A complex heatmap object containing a heatmap for each sample (each bam file),
#' sorted by the read counts in the middle window (around peak summit) of the first sample (bam file) that was provided.
#'
#' @importFrom ComplexHeatmap Heatmap
#' @importFrom ComplexHeatmap HeatmapAnnotation
#' @importFrom ComplexHeatmap anno_text
#' @importFrom ComplexHeatmap max_text_width
#' @importFrom grid gpar
#' @importFrom grid unit
#' @importFrom circlize colorRamp2
#'
#' @export
DrawSummitHeatmaps <- function(counts, bamNames, nicebamNames = bamNames, plotcols = circlize::colorRamp2(c(0, 3), c("white", "darkblue"))){
order.sample <- 1
counts.log <- (counts[[bamNames[order.sample]]])
zero.inx <- which(colnames(counts.log) == 0)
counts.sorted <- counts.log[order(counts.log[,zero.inx]),]
counts.sorted.rev <- apply(counts.sorted,2,rev)

ht_list = NULL
binnames <- ifelse((as.numeric(colnames(counts.sorted.rev))/1000)%%1==0,colnames(counts.sorted.rev),"")

for (bam.sample in seq_along(bamNames)){

  counts.log <- (counts[[bamNames[bam.sample]]])
  counts.sorted <- counts.log[row.names(counts.sorted.rev),]

  ht_list <- ht_list + Heatmap(counts.sorted,name = bamNames[bam.sample], cluster_rows = FALSE, cluster_columns=FALSE,
                               column_order = colnames(counts.sorted), col = plotcols,
                               column_title = nicebamNames[bam.sample], column_title_gp = gpar(fontsize = 20, fontface = "bold"),
                               show_row_names = FALSE, show_column_names = FALSE,
                               bottom_annotation = HeatmapAnnotation(
                                 text = anno_text(binnames, rot = 45, offset = unit(1, "npc"), just = "right",gp=gpar(fontsize=10,fontface = "italic")),
                                 annotation_height = max_text_width(binnames)),use_raster = TRUE, raster_device = "png",raster_quality=1
   )

  }
return(ht_list)
}
