#' @title Log2Transform
#'
#' @description This function takes a list of matrices and calculates the log2 for each value.
#' If (and only if) at least one value in a given matrix is 0, a pseudocount is added first to all values.
#'
#' @param counts A list of counts across peak summits generated by SummitHeatmap.
#' @param pseudocount The pseudocount to add to the values (to avoid taking the log2 of 0). Default=1.
#'
#' @return A list of matrices of same size as counts, with all the values log2 transformed.
#'
Log2Transform <- function(counts, pseudocount=1){
if(length(counts[counts==0])>0){
  counts.log <- log2(counts + pseudocount)
} else {
  counts.log <- log2(counts)
  return(counts.log)
}
}
