#' @title SummarizeHeatmaps
#'
#' @description Summarize heatmap count matrices from individual bam samples.
#'
#' @details This function takes a list of heatmap count matrices (from individual bam files) and summarizes them (by user defined groups).
#' The matrices should have unique row names.
#'
#' @param counts A list of counts across peak summits generated by SummitHeatmap.
#' @param sampleList A list where each element is a character vector of sample names that should be grouped.
#' The name of each element of this list specifies the group name.
#' @param summarizing Defines the way in which the counts are summarized. Defaults to mean.
#'
#' @return A list of summarized (by group) counts across peak summits.
#'
#' @importFrom plyr laply
#'
#' @examples
#' counts <- list(matrix(rnorm(21000,2,1),ncol=21,nrow=100,dimnames=list(1:100,-10:10)),
#'                matrix(rnorm(21000,2,1),ncol=21,nrow=100,dimnames=list(1:100,-10:10)),
#'                matrix(rnorm(21000,2,1),ncol=21,nrow=100,dimnames=list(1:100,-10:10)),
#'                matrix(rnorm(21000,2,1),ncol=21,nrow=100,dimnames=list(1:100,-10:10)))
#' bamNames <- c("counts1","counts2","counts3","counts4")
#' names(counts) <- bamNames
#' SummarizeHeatmaps(counts,sampleList=list(countsA=c("counts1","counts2"),countsB=c("counts3","counts4")))
#'
#' @export
SummarizeHeatmaps <- function(counts,sampleList,summarizing = mean){
  if (length(which(duplicated(row.names(counts[[1]]))==TRUE))>0){
    stop(sprintf("Error: The first counts table in your list contains %d duplicated rownames.\n
         Please provide unique rownames for all tables.",length(which(duplicated(row.names(counts[[1]]))==TRUE))))
  } else {

  meanCounts <- lapply(1:length(sampleList), matrix,  nrow=0, ncol=0)
  names(meanCounts) <- names(sampleList)
  for (i in seq_along(sampleList)) {
    print(sprintf("summarizing group %s",names(meanCounts)[i]))
    #meanCounts[[i]] <- plyr::aaply(plyr::laply(counts[sampleList[[i]]], as.matrix), c(2, 3), summarizing)
    meanCounts[[i]] <- apply(plyr::laply(counts[sampleList[[i]]], as.matrix), 2:3, summarizing)
    
  }
  return(meanCounts)
  }
}
